rules = [
  RemoveUnused,
  LeakingImplicitClassVal,
  ProcedureSyntax,
  NoAutoTupling,
  DisableSyntax
]

DisableSyntax {
  noVars = false
  noNulls = false
  noReturns = false
  noWhileLoops = false
  noXml = true
}

RemoveUnused {
  imports = true
  privates = true
  locals = true
  patternvars = true
  params = false
}
